# Generated by Django 3.0.6 on 2020-11-04 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('age', models.PositiveIntegerField(default=0, verbose_name='Возраст')),
                ('coutry', models.CharField(max_length=50, verbose_name='Страна')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('genre', models.CharField(max_length=50, verbose_name='Жанр')),
                ('year', models.CharField(verbose_name='Год выхода', max_length=4)),
                ('producer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmapp.Producer', verbose_name='Режиссер')),
            ],
        ),
    ]
