# Generated by Django 3.0.6 on 2020-11-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.CharField(max_length=4, verbose_name='Год'),
        ),
    ]
