# Generated by Django 3.0.6 on 2020-11-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0002_auto_20201104_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producer',
            old_name='coutry',
            new_name='country',
        ),
        migrations.AlterField(
            model_name='film',
            name='producer_name',
            field=models.CharField(max_length=4, verbose_name='Режиссер'),
        ),
    ]
