# Generated by Django 3.0.6 on 2020-11-04 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0003_auto_20201104_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='producer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmapp.Producer'),
        ),
    ]
