# Generated by Django 3.0.6 on 2020-11-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0004_auto_20201104_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='slug',
            field=models.SlugField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='slug',
            field=models.SlugField(default=0, unique=True),
        ),
    ]
