# Generated by Django 3.0.6 on 2020-11-06 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0005_auto_20201106_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='slug',
        ),
    ]
