# Generated by Django 3.0.6 on 2021-01-17 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0006_auto_20201106_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='producer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filmapp.Producer'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='producer_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Имя'),
        ),
    ]
